const mongoose=require('mongoose');const {Schema}=mongoose;
const userSchema=new Schema({id:{type:String,unique:true,index:true},username:String,firstName:String,lastName:String,lastSeenAt:Date},{timestamps:true});
const groupSchema=new Schema({id:{type:String,unique:true,index:true},title:String,type:String,username:String,approved:{type:Boolean,default:false},lastSeenAt:Date},{timestamps:true});
const giveawaySchema=new Schema({channelId:{type:String,index:true},channelPostId:{type:Number,index:true},discussionChatId:String,title:String,status:{type:String,enum:['active','picking','completed','cancelled','expired'],default:'active',index:true},winnerCount:{type:Number,default:1,min:1,max:100},reserveWinnerCount:{type:Number,default:0,min:0,max:100},durationSeconds:{type:Number,default:20,min:0,max:120},createdBy:String,createdAt:{type:Date,default:Date.now},pickedAt:Date,rules:{keyword:String,requireUsername:{type:Boolean,default:false},requireBotStart:{type:Boolean,default:false},excludeAdmins:{type:Boolean,default:true}},pickRound:{type:Number,default:0},pickerMessageId:Number,stateVersion:{type:Number,default:0}},{timestamps:true});
giveawaySchema.index({channelId:1,channelPostId:1},{unique:true,sparse:true});
const entrySchema=new Schema({giveawayId:{type:Schema.Types.ObjectId,ref:'Giveaway',index:true},channelId:String,channelPostId:Number,groupChatId:String,userId:String,username:String,firstName:String,lastName:String,commentMessageId:Number,commentText:String,eligible:{type:Boolean,default:true},rejectedReason:String,enteredAt:{type:Date,default:Date.now}});
entrySchema.index({giveawayId:1,userId:1},{unique:true});
entrySchema.index({giveawayId:1,eligible:1,userId:1});
entrySchema.index({giveawayId:1,eligible:1,enteredAt:1});
const paidReactionSchema=new Schema({giveawayId:{type:Schema.Types.ObjectId,ref:'Giveaway',index:true},channelId:{type:String,index:true},channelPostId:{type:Number,index:true},userId:String,username:String,firstName:String,lastName:String,active:{type:Boolean,default:true,index:true},lastReactionAt:{type:Date,default:Date.now}},{timestamps:true});
paidReactionSchema.index({giveawayId:1,userId:1},{unique:true});
paidReactionSchema.index({giveawayId:1,active:1,userId:1});

const winnerSchema=new Schema({giveawayId:{type:Schema.Types.ObjectId,ref:'Giveaway',index:true},round:{type:Number,default:1},userId:String,username:String,firstName:String,lastName:String,rank:Number,selectedAt:{type:Date,default:Date.now},status:{type:String,enum:['winner','rerolled','void'],default:'winner'}});
winnerSchema.index({giveawayId:1,round:1,userId:1},{unique:true});
const broadcastSchema=new Schema({text:String,targets:[{chatId:String,status:{type:String,enum:['pending','sent','failed'],default:'pending'},attempts:{type:Number,default:0},error:String}],status:{type:String,enum:['queued','running','completed','partial','failed'],default:'queued'},createdBy:String,startedAt:Date,finishedAt:Date},{timestamps:true});
const auditSchema=new Schema({action:String,actorId:String,giveawayId:Schema.Types.ObjectId,targetId:String,meta:Schema.Types.Mixed,createdAt:{type:Date,default:Date.now}});
module.exports={User:mongoose.model('UserV2',userSchema,'users'),Group:mongoose.model('GroupV2',groupSchema,'groupchats'),Giveaway:mongoose.model('GiveawayV2',giveawaySchema,'giveawayposts'),Entry:mongoose.model('EntryV2',entrySchema,'entries'),PaidReaction:mongoose.model('PaidReactionV2',paidReactionSchema,'paidreactions'),Winner:mongoose.model('WinnerV2',winnerSchema,'winnerhistories'),BroadcastJob:mongoose.model('BroadcastJobV2',broadcastSchema,'broadcastjobs'),AuditEvent:mongoose.model('AuditEventV2',auditSchema,'auditevents')};